export enum TILE_TYPE_ENUM{
    WALL_ROW = 'WALL_ROW',
    WALL_COLUMN = 'WALL_COLUMN',
    WALL_LEFT_TOP = 'WALL_LEFT_TOP',
    WALL_LEFT_BOTTOM = 'WALL_LEFT_BOTTOM',
    WALL_RIGHT_TOP = 'WALL_RIGHT_TOP',
    WALL_RIGHT_BOTTOM = 'WALL_RIGHT_BOTTOM',
    CLIFF_RIGHT = 'CLIFF_RIGHT',
    CLIFF_CENTER = 'CLIFF_CENTER',
    CLIFF_LEFT = 'CLIFF_LEFT',
    FLOOR = 'FLOOR',
}

export enum EVENT_NAME{
    NEXT_LEVEL = 'NEXT_LEVEL',
    PLAYERCTRL = 'PLAYERCTRL',
    PLAYERANIM = 'PLAYERANIM',
}

export enum INPUT_ENUM{
    LEFT = 'LEFT',
    RIGHT = 'RIGHT',
    TOP = 'TOP',
    BOTTOM = 'BOTTOM',
    TURNLEFT = 'TURNLEFT',
    TURNRIGHT = 'TURNRIGHT'
}

export enum ANIM_NAME{
    IDLE = 'IDLE',
    TURNLEFT = 'TURNLEFT',
}

export enum DIRECTION{
    TOP = 'TOP',
    BOTTOM = 'BOTTOM',
    LEFT = 'LEFT',
    RIGHT = 'RIGHT',
}
